### ISSUE TITLE
Add Contributing.md

### ISSUE THREAD

**Issue by okonet** [react-dropzone/attr-accept#20]
The document should state 

1. the workflow,
1. the fact this repo uses semantic-release
1. the fact it uses angular commit messages

**Comment by okonet** [comment]
cc @ajsharp

**Comment by ajsharp** [comment]
Here's a potential first draft of the workflow section:

### Development

**All changes** should be done on a branch and submitted as pull requests. Make sure your changes pass CI before submitting a pull request.

**Comment by okonet** [comment]
@ajsharp Please create a PR :)

**Comment by rolandjitsu** [comment]
We can use https://github.com/react-dropzone/react-dropzone/blob/master/CONTRIBUTING.md. We should probably make a note about the release part in both repos.
