### ISSUE TITLE
Certain file types are not allowed

### ISSUE THREAD

**Issue by rxmarbles** [react-dropzone/attr-accept#30]
Per this issue in [react-dropzone](https://github.com/react-dropzone/react-dropzone/issues/644)
It seems the check on file types has been changed in browser support as it makes those that have a filetype that includes a `.` to a blank string. The example here is a .stl file. This is an example file from a basic input file type tag

```
File(7138484) {name: "Apollo_11.stl", lastModified: 1440523936000, lastModifiedDate: Tue Aug 25 2015 10:32:16 GMT-0700 (Mountain Standard Time), webkitRelativePath: "", size: 7138484, …}
lastModified
:
1440523936000
lastModifiedDate
:
Tue Aug 25 2015 10:32:16 GMT-0700 (Mountain Standard Time) {}
name
:
"Apollo_11.stl"
size
:
7138484
type
:
"model/x.stl-binary"
webkitRelativePath
:
""
__proto__
:
File
```

**Comment by okonet** [comment]
Is this actionable somehow? Can you come up with a fix for it?

**Comment by rkmarks** [comment]
Not entirely sure @okonet. I'm still debugging in this repo to see where this occurs

**Comment by squancy** [comment]
@rxmarbles Have you come up with a solution?

**Comment by LEEILLJIN** [comment]
i'm facing this problem. How i solve this issue?

**Comment by rolandjitsu** [comment]
@rxmarbles do you think you have time to pick this up? Or should we go ahead and close (we can reopen when others encounter it and look into it then)?

**Comment by rolandjitsu** [comment]
Closing this for now. We can reopen, if needed, later on.
