### ISSUE TITLE
Accept custom extensions like html file input

### ISSUE THREAD

**Issue by larissa-n** [react-dropzone/attr-accept#32]
In `<input type='file'>`, the fact that you can use the `accept` prop for random extensions (like `accept='myext'`) is rather handy for all those that create and use proprietary file types.

Getting into react-dropzone, is it true that [this example](https://github.com/react-dropzone/react-dropzone/issues/276#issuecomment-432628384) by @export-mike (copied below) is currently the best shot?

> Pseudo code:
> 
> ```js
> < ... accept="" onDrop={file => {
>  if(!file.name.endsWith('.csv')) { this.setState({ rejected: true }) }
>  // doSomething();
> } >
> ```

Are there any plans for extending the accept prop in the same way file inputs work? When users browse files, it's nice to have them filtered by the extension(s) that'll work.

Thank you!

**Comment by rolandjitsu** [comment]
@larissa-n there have been a lot of changes in react-dropzone. I suggest checking out the latest version and see if that suits your needs.

Gonna close this for now.
