### ISSUE TITLE
Last fix was not published on npm

### ISSUE THREAD

**Issue by rolandjitsu** [react-dropzone/attr-accept#34]
It seems like https://github.com/react-dropzone/attr-accept/commit/5d4cdf8874ea9e88cd47da1f1d51430c6f10c708 was not published on npm due to some error on Travis:

```
after_success
1.36s$ travis-deploy-once "npm install -g semantic-release@13 && semantic-release"
{ HTTPError: Response code 403 (Forbidden)
    at stream.catch.then.data (/home/travis/build/react-dropzone/attr-accept/node_modules/got/index.js:341:13)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:189:7)
  name: 'HTTPError',
  host: 'api.travis-ci.org',
  hostname: 'api.travis-ci.org',
  method: 'POST',
  path: '/auth/github',
  protocol: 'https:',
  url: 'https://api.travis-ci.org/auth/github',
  statusCode: 403,
  statusMessage: 'Forbidden',
  headers: 
   { connection: 'close',
     server: 'nginx',
     date: 'Sat, 12 Oct 2019 05:22:35 GMT',
     'content-type': 'application/json',
     'transfer-encoding': 'chunked',
     'strict-transport-security': 'max-age=31536000',
     'x-endpoint': 'Travis::Api::App::Endpoint::Authorization',
     'x-pattern': '/github',
     'x-oauth-scopes': 'public',
     'x-accepted-oauth-scopes': 'public',
     vary: 'Accept,Accept-Encoding',
     'content-encoding': 'gzip',
     'x-rack-cache': 'invalidate, pass',
     'x-request-id': '117769e9-6c3a-414c-b2c5-f54c1bcba3a1',
     'access-control-allow-origin': '*',
     'access-control-allow-credentials': 'true',
     'access-control-expose-headers': 'Content-Type, Cache-Control, Expires, Etag, Last-Modified, X-Request-ID',
     via: '1.1 vegur' } }
```

Is it possible that we're missing some token or whatever token we used expired?

This change would probably also fix https://github.com/react-dropzone/react-dropzone/issues/887.

**Comment by okonet** [comment]
Not sure. I didn’t do anything. Can we switch to GitHub automations?

**Comment by rolandjitsu** [comment]
Could you try generating a new github token and npm token and replace it in Travis? I can also generate a github token, but I cannot publish to npm as I think it's published under your personal username.

We could, but I don't have time at the moment to do it.

**Comment by rolandjitsu** [comment]
Could be related to https://github.com/semantic-release/semantic-release/issues/688.

**Comment by okonet** [comment]
I also don’t have time. What is required from me to remove it from my personal organization and move to this one?

**Comment by rolandjitsu** [comment]
I just created an org on npm **react-dropzone**. I think if we follow [these steps](https://docs.npmjs.com/transferring-a-package-from-a-user-account-to-an-org) we should be able to transfer the package(s).

**Comment by rxmarbles** [comment]
@okonet @rolandjitsu I can help, sorry I've been afk. Work project has been taking up a lot of my time. I can add you @rolandjitsu as maintainer once I'm at my laptop

**Comment by rxmarbles** [comment]
@rolandjitsu can you add me to the npm org as well when you can

**Comment by rolandjitsu** [comment]
@rxmarbles thanks. Do you also have access to the npm packages? I need to be admin to be able to move those to the org. I just sent you an invite.

**Comment by rxmarbles** [comment]
@rolandjitsu I don't have access to them in npm unfortunately

**Comment by rolandjitsu** [comment]
@rxmarbles that's ok, @okonet can do it when he has time. I just need to be admin of this repo so that semantic-version can push the release commits.

**Comment by okonet** [comment]
I screwed the invitation and it has expired. Can someone invite me to npm org again? I'll transfer rights then.

**Comment by rolandjitsu** [comment]
@okonet sure thing. Is *andrey@okonet.ru* still your email?

**Comment by okonet** [comment]
Yep

**Comment by rolandjitsu** [comment]
Sent it 😄

**Comment by rolandjitsu** [comment]
@okonet meanwhile, could you give me push permissions to this repo so I can publish the latest version?

**Comment by okonet** [comment]
@rolandjitsu still can't see it :(

**Comment by okonet** [comment]
As for rights, you should have plenty of them:

![CleanShot 2019-10-28 at 08 29 50](https://user-images.githubusercontent.com/11071/67659655-2506fb00-f95d-11e9-9865-8a5c83bfba7c.png)

**Comment by okonet** [comment]
@rolandjitsu I'm on npm now but not sure what to do now. I can invite maintainer to it but there is no option to move it to an org. Do you know how to do that?

**Comment by rxmarbles** [comment]
Basically @okonet you just need to invite us to your packages in npm as maintainers and once you do that we can add it to the org, you can also add it to the org now that you are an member of the npm org

**Comment by rolandjitsu** [comment]
> As for rights, you should have plenty of them:
> 
> ![CleanShot 2019-10-28 at 08 29 50](https://user-images.githubusercontent.com/11071/67659655-2506fb00-f95d-11e9-9865-8a5c83bfba7c.png)

Thanks. I tried to rebuild on Travis a couple of times but it keeps telling me I don't have enough permissions. I will investigate further these days to see if it's something else at fault.

**Comment by rolandjitsu** [comment]
> @rolandjitsu I'm on npm now but not sure what to do now. I can invite maintainer to it but there is no option to move it to an org. Do you know how to do that?

As @rxmarbles suggested, you can do it as well as both you and @rxmarbles are admins and you can add new packages.

From the npm organization section, navigate to teams, then select packages under the developers team and there is the add existing package input where you can add this package and react-dropzone package as well.

This shouldn't require a change in npm token on Travis, it should still work. But it will also allow me and @rxmarbles to publish as well when needed.

**Comment by rxmarbles** [comment]
@okonet are you still having issues accepting the invite to the org? if so @rolandjitsu can you make me an owner of the org? i would like to try something to re-send the invite. If that does not work I will have npmjs support handle adding @okonet to the org so we can get the packages moved. I would also like to see about setting up github actions to handle upgrades w/ their registry perhaps.

**Comment by okonet** [comment]
Npm org page looks like this for me so I don't know how to add a package there:

![CleanShot 2019-11-13 at 20 37 12](https://user-images.githubusercontent.com/11071/68797723-671a8700-0655-11ea-8d18-a2e0a7b1f82e.png)

Actually what I also don't get is why do we need to manually release something? I'm going to update the token on this package and try re-building it.

**Comment by okonet** [comment]
Okay invited you both to the package. I didn't know you can have maintainer on npm ¯\_(ツ)_/¯

**Comment by okonet** [comment]
@rxmarbles Is that enough from my side? Or do I need to do something with Travis setup? I can't wait to move away from 3 different platforms that needed to release a version

**Comment by okonet** [comment]
Can someone take some time and setup it over the GitHub Actions instead of Travis?

**Comment by rxmarbles** [comment]
that's perfect @okonet i added the package to the npm org. When you have a chance can you add us both to the `react-dropzone` package in npm as well so we can do the same?

**Comment by okonet** [comment]
Sure thing!

**Comment by okonet** [comment]
✅

**Comment by rxmarbles** [comment]
@okonet nothing else should be needed on your side, I think at this point @rolandjitsu are you able to generate tokens and update them in travisci now? if you cannot i can tomorrow

**Comment by rolandjitsu** [comment]
I will update the tokens this weekend. But the issue I had was with the Git auth, standard-version keeps refusing to auth. I'm hoping I will have some time this weekend to look into it.

**Comment by okonet** [comment]
I still think the way to go would be to switch to GitHub Actions to reduce the complexity with auth etc.

**Comment by rolandjitsu** [comment]
Fixed with https://github.com/react-dropzone/attr-accept/pull/37.
