### ISSUE TITLE
Empty string vs empty array inconsistency

### ISSUE THREAD

**Issue by ThiefMaster** [react-dropzone/attr-accept#38]
If `acceptedFiles` is an empty string, everything is accepted, but if it's an empty array, nothing is accepted. Is this intentional?

**Comment by rolandjitsu** [comment]
Probably not, just submit a PR and add a test case for it.

**Comment by rolandjitsu** [comment]
I guess this wasn't a major issue. I'll try to see if I can reproduce and fix.
