### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by yiioverflow** [react-dropzone/attr-accept#44]

**Comment by rolandjitsu** [comment]
@yiioverflow what demo are you referring to? Could you be more specific?

**Comment by yiioverflow** [comment]
@rolandjitsu orryfor the late reply.  Its a portfolio website made up with react.

**Comment by rolandjitsu** [comment]
Ok, that's not very helpful. I will close this issue for now. If you'll provide a proper reproducible example we can reopen.
