### ISSUE TITLE
ESM build?

### ISSUE THREAD

**Issue by edemaine** [react-dropzone/attr-accept#63]
**Is your feature request related to a problem? Please describe.**
When including `attr-accept` in an ESM library, Vite fails to properly convert from CJS to ESM. See https://github.com/soorria/solid-dropzone/issues/3 for a real-world example.

**Describe the solution you'd like**
Offer an ESM build parallel to the current CJS options. I believe a larger Webpack configuration can do this relatively easily.

**Describe alternatives you've considered**
Forking just to produce our own ESM build.

**Comment by okonet** [comment]
Feel free to submit a PR. I have no idea how to do this.

**Comment by rolandjitsu** [comment]
I think that https://github.com/react-dropzone/attr-accept/pull/66 addresses that @edemaine . But I appreciate your contribution! Let me know if the other PR is missing anything you needed.

**Comment by rolandjitsu** [comment]
This should be available with v3.0.0-beta.1.
