### ISSUE TITLE
[BUG] Module not found: Error: Can't resolve 'attr-accept' in '/path'

### ISSUE THREAD

**Issue by bcattonsimply** [react-dropzone/attr-accept#70]
**Describe the bug**
I am getting this error when I try to install react-dropzone.

Module not found: Error: Can't resolve 'attr-accept' in '/path'

**To Reproduce**
1. try to install react-dropzone.

**Expected behavior**
This was working prior to the latest version release.

**Desktop (please complete the following information):**
 - macOs Sequioa

**Additional context**

**Comment by rolandjitsu** [comment]
Probably related to https://github.com/react-dropzone/attr-accept/issues/71.
