### ISSUE TITLE
Yank/Unpublish 2.2.3

### ISSUE THREAD

**Issue by adhami3310** [react-dropzone/attr-accept#74]
As that package version is unusable, it must be yanked as soon as possible. A separate hotfix should be done but only after the package is back at a working stage. Even if the hotfix is merged, an unworking version must always be yanked.

**Comment by rolandjitsu** [comment]
It doesn't really make sense to me to do that since semver dictates to use the latest patch, which is what could be causing issues. Unless you specifically pin down to the broken version, package managers should pick up the latest patch.

For now, I'll keep the versions as are unless the patch doesn't get published.

**Comment by adhami3310** [comment]
Let's listen to crates.io as NPM doesn't speak on the issue:

> Crates should only be yanked in exceptional circumstances, for example, an accidental publish, an unintentional SemVer breakages, or a significantly broken and unusable crate.

I believe "significantly broken and unusable" is grounds for unpublishing this version.

**Comment by rolandjitsu** [comment]
If you can reproduce a use case in which leaving as is causes an issue
(without installing 2.2.3 specifically), I'd be more than happy to
unpublish.

**Comment by Alek99** [comment]
I don't quite understand this logic of having downstream users prove an unusable release is a problem, when it can be simply removed. Mistakes happen that why unpublish commands exists.  If the version has no functional utility and doesn't run why keep it, is it to just maintain continuity in versioning?

It's your library so you can do whatever you want at the end of the day. It's just not good practice imo as a library with many down stream dependents.

**Comment by rolandjitsu** [comment]
The reasoning is simple: we let the semver take care of the issue. There's
a patch that should take care of the issue. If there are further issues,
we'll look into it.

Removing a previous version has no value at this point unless it really is
causing issue.
